### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by jonnor**

### CODE REVIEW

**Comment by jonnor** [comment]
Note that the online example URLs will be 404 until we merge this, and then update `gh-pages`.

**Comment by forresto** [comment]
I don't have write access.

**Comment by jonnor** [comment]
@forresto you should have been invited to be collaborator on the repo some two weeks ago. Check your email?

**Comment by forresto** [comment]
I'm a collab, but can't push / merge master.

**Comment by ei-grad** [comment]
@jonnor @forresto its 404 now :-)

**Comment by jonnor** [comment]
@ei-grad what exactly is a 404 now?

**Comment by ei-grad** [comment]
https://flowhub.github.io/the-graph/examples/demo-thumbnail.html

**Comment by jonnor** [comment]
@ei-grad thanks, should be fixed now! That was a new example which had never actually been pushed to Github Pages.

**Pull request merged**
