### PR TITLE
Initial test setup

### PR DESCRIPTION
**Pull request by jonnor**

### CODE REVIEW

**Comment by jonnor** [comment]
Test is passing here in Chrome. Think maybe we should use Karma (or similar) to run tests on Chrome/Firefox also on Travis CI.

**Comment by jonnor** [comment]
But for #287 it would be nice to have basic PhantomJS coverage.

**Comment by bergie** [comment]
We could also use Saucelabs, like we do for noflo-ui

**Comment by jonnor** [comment]
Not very impressed with Saucelabs from that experience. Especially checking
the error is tedious

**Comment by bergie** [comment]
No PhantomJS support in Polymer yet https://github.com/Polymer/project/issues/20

**Comment by bergie** [comment]
@jonnor the cross-browser tests run now, but both IE and Safari fail. Chrome is happy, though

**Comment by bergie** [comment]
@jonnor passes when testing only Chrome. We should look at the cross-browser situation, but before that even the current state would be good to merge to get at least some smoketesting in.

**Pull request merged**
