### PR TITLE
Fix TouchEvent support

### PR DESCRIPTION
**Pull request by jonnor**
Affects iOS devices

### CODE REVIEW

**Comment by bergie** [comment]
@jonnor dragging nodes and pinch-zoom both work on iOS. Making edges also works, though is a pretty tricky to hit the small target. However, if I long-press a node, menu doesn't show up, and after that dragging and zooming is also dead

**Comment by jonnor** [comment]
Any exceptions? Any console output? Does this only happen when opening menu on a node, or also on the background or an edge?

**Comment by bergie** [comment]
@jonnor 
`TypeError: null is not an object (evaluating 'this.props.menus[options.type]')`

(this is with `examples/simple.html`)

**Comment by jonnor** [comment]
Thats probably fixed by https://github.com/flowhub/the-graph/pull/362/commits/72af77bd7f8f5db227da36dcd8eeab9ba2e85890
It should not happen in `demo-full.html`. Can you verify?

**Comment by bergie** [comment]
@jonnor can verify fully working in `demo-full.html`. Great work! Works also nicely with the Apple Pencil (which does supply [some extra data](https://github.com/w3c/touch-events/pull/81), but I don't think we have uses for that so far)

**Pull request merged**
